spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${SPRING_DATASOURCE_USERNAME:wallet_user}
    password: ${SPRING_DATASOURCE_PASSWORD:wallet_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true

  data:
    redis:
      url: ${REDIS_URL:${INTERNAL_URL:}}
      host: ${REDIS_HOST:${SPRING_DATA_REDIS_HOST:localhost}}
      port: ${REDIS_PORT:${SPRING_DATA_REDIS_PORT:6379}}
  redisson:
    address: ${REDIS_URL:${INTERNAL_URL:redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}}}


  cache:
    type: redis


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

momo:
  secret-key: ${MOMO_SECRET_KEY:my-super-secret-key-123}

jwt:
  secret: ${JWT_SECRET:my-super-wallet-secure-secret-key-default-value}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

